### ISSUE TITLE
READMEを置く

### ISSUE THREAD

**Issue by Mamonbo** [titech-ssr/blog.rogiken.org#2]
ポみたいな情報量のものでもあった方がいい？
それとも意図的に置いていない？

**Comment by lo48576** [comment]
置き忘れてました(まだ作ってないです)
ポは流石に雑すぎだけど、まあ適当に用意したいですね

**Comment by lo48576** [comment]
https://github.com/titech-ssr/blog.rogiken.org/commit/95c3c3fd5536e77547aa67f0cdec5a3d171a900f にて修正しました
